In [1]:
import os
from glob import glob
import numpy as np
import nibabel as nib
import torch
import pandas as pd
from torch import nn
from torch import optim
from torch.utils.data import TensorDataset, DataLoader, Dataset
from torch.autograd import Variable
from torchvision import transforms
import torch.nn as nn
from sklearn.metrics import roc_auc_score, average_precision_score
import tqdm
from operator import add
import matplotlib.pyplot as plt
import easydict

In [20]:
label_data = pd.read_csv('/home/chaeeun/Desktop/brain disease prediction/fileIO/current_label.csv') 
label_data

FOLDERNAME  \
0    14090110_20180523_095025_MR   
1    14152551_20180129_085254_MR   
2    15168092_20180223_091548_MR   
3    16657951_20180529_103505_MR   
4    16965739_20180419_103601_MR   
..                           ...   
716  50037843_20171114_091144_MR   
717  50055081_20171117_102431_MR   
718  50121212_20171211_101705_MR   
719  50137402_20171213_112244_MR   
720  50166424_20171227_081024_MR   

     Cerebral WM Hypointensities* Total Percent Of Icv  \
0                                               0.0249   
1                                               0.1131   
2                                               0.1630   
3                                               0.0740   
4                                               0.0991   
..                                                 ...   
716                                             0.0191   
717                                             0.0197   
718                                             0.0580   
719                                             0.1420   
720                                             0.0128   

     Cortical Gray Matter Total Percent Of Icv  \
0                                      30.7874   
1                                      31.9052   
2                                      30.3495   
3                                      30.7348   
4                                      30.3336   
..                                         ...   
716                                    31.8404   
717                                    32.0220   
718                                    32.8894   
719                                    30.5600   
720                                    32.9095   

     Ventricle Total Percent Of Icv  \
0                            1.9233   
1                            2.6646   
2                            3.3834   
3                            2.1675   
4                            2.2278   
..                              ...   
716                          4.2057   
717                          1.3715   
718                          2.2994   
719                          3.0031   
720                          2.1404   

     Cerebral White Matter Total Percent Of Icv  \
0                                       30.4758   
1                                       30.7423   
2                                       28.8604   
3                                       31.3847   
4                                       30.6224   
..                                          ...   
716                                     29.7961   
717                                     33.6114   
718                                     29.1374   
719                                     30.8935   
720                                     29.7731   

     Whole Brain Total Percent Of Icv  
0                             75.8345  
1                             77.1605  
2                             71.4136  
3                             75.1116  
4                             75.7314  
..                                ...  
716                           74.6269  
717                           79.2204  
718                           75.7103  
719                           74.9438  
720                           76.9283  

[721 rows x 6 columns]

In [21]:
label_data.drop('FOLDERNAME',axis='columns', inplace=True)

In [22]:
label_data.shape

(721, 5)

In [ ]:
unnorm_label = label_data.to_numpy(copy = True)
label = label_data.to_numpy(copy = False)
type(label)
unnorm_label[0], label[0]

(array([2.49000e-02, 3.07874e+01, 1.92330e+00, 3.04758e+01, 7.58345e+01]),
 array([2.49000e-02, 3.07874e+01, 1.92330e+00, 3.04758e+01, 7.58345e+01]))

In [ ]:
def normalize(label):
    for i in range(5):
        y = label[:, i]
        label[:, i] = (y - y.mean())/y.std()

In [ ]:
normalize(label)

In [ ]:
label[0], unnorm_label[0]

(array([-0.43159864, -0.87598003, -0.36621553,  0.02377017, -0.32168956]),
 array([2.49000e-02, 3.07874e+01, 1.92330e+00, 3.04758e+01, 7.58345e+01]))

In [ ]:
!pwd

/home/chaeeun/Desktop/brain disease prediction


In [ ]:
np.save( './labels/721_normed_label', label,allow_pickle=True, fix_imports=True)
np.save('./labels/721_unnormed_label', unnorm_label, allow_pickle=True, fix_imports=True)

In [23]:
label_1 = label_data['Cerebral WM Hypointensities* Total Percent Of Icv']
label_2 = label_data['Cortical Gray Matter Total Percent Of Icv']
label_1 = label_1.values.reshape(-1,1)
label_2 = label_2.values.reshape(-1,1)
np.save('./labels/label_1', label_1, allow_pickle = True, fix_imports = True)
np.save('./labels/label_2', label_2, allow_pickle = True, fix_imports = True)